# Generated by Django 4.1.3 on 2022-11-03 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musicplaylist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_title', models.CharField(max_length=50, null=True)),
                ('playlist_content', models.TextField(null=True)),
                ('playlist_create_at', models.DateTimeField(auto_now_add=True)),
                ('playlist_update_at', models.DateTimeField(auto_now=True)),
                ('playlist_likes', models.ManyToManyField(related_name='playlist_likes_set', to=settings.AUTH_USER_MODEL)),
                ('playlist_select_musics', models.ManyToManyField(related_name='select_musics_set', to='musicplaylist.music')),
                ('playlist_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='MusicPlayList',
        ),
    ]
