# Generated by Django 4.1.3 on 2022-11-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicplaylist', '0002_playlist_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='is_main_recom',
            field=models.BooleanField(default=False),
        ),
    ]
