# Generated by Django 4.1.3 on 2022-11-03 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicplaylist', '0002_playlist_delete_musicplaylist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='music_user',
        ),
    ]
