# Generated by Django 4.1.3 on 2022-11-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicplaylist', '0003_remove_music_music_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='music_artist',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='music',
            name='music_genre',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='music',
            name='music_title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
